### ISSUE TITLE
Comment tag search in sherlodoc

### ISSUE THREAD

**Issue by sim642** [art-w/sherlocode#1]
Thanks for the neat service! I recently noticed the appearance of sherlodoc, which doesn't seem to have a separate repository, so I'm opening this issue here.

It would be nice to also search by tags in documentation comments, e.g. `@raise Not_found`. I guess right now it just tries to find that from function names and returns nothing.

**Comment by art-w** [comment]
Thanks for the suggestion! Sherlodoc is still a bit shaky at this point to be released, but I was looking for some early feedback on what needed to be improved :)

You're right that it only searches in the `Module.value` names and types, and ignores the documentation comment at this point... but I was thinking of doing stemming for this natural language bit because I didn't anticipate the need for `@raise`. It actually sounds useful and easier to support than the real docstring search, I'll take a look when I get some time to work on it :)

**Comment by art-w** [comment]
I'm happy to report that there has been some progress on this issue, as sherlodoc now indexes and searches in the documentation comments: e.g. [`raise Not_found`](https://doc.sherlocode.com/?q=raise%20Not_found) finds some interesting stuff that it couldn't see before :) (thanks to the work of @EmileTrotignon and @panglesd to better integrate it with odoc!)

However, it seems that `@raise` odoc tags are specifically ignored!.. So it's not quite there yet, but we have a new issue at https://github.com/art-w/sherlodoc/issues/11 to keep track of this in the other repo.
